### ISSUE TITLE
P2304 Improve type generic programming

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#16]
Issue tracking the SG22 discussion of [P2304R0](https://wg21.link/p2304r0) Improve type generic programming (Jens Gustedt)

[wg21 issue](https://github.com/cplusplus/papers/issues/990)

**Comment by ThePhD** [comment]
This proposal is an overview for a set of proposals. Some of them have already been accepted (e.g. the `auto` feature for C is in C23 for object returns). Other parts will be taken care of later (potentially, such as `auto` for parameters in C), but there is no compatibility risk here because the Lambdas portion of the code is meant to be directly compatible with C++.
